---
- name: Install Docker and launch a container
  hosts: all
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started

    - name: Pull a Docker image
      community.docker.docker_image:
        name: nginx
        state: present

    - name: Run a Docker container
      community.docker.docker_container:
        name: my_nginx
        image: nginx
        ports:
          - "80:80"

