---

- name: test the loops
  hosts: all
  become: true
  vars:
    v_name: "devil"

  tasks:
    - name: loops
      apt:
        name: "{{ item }}"           # loops will catch this package names
        state: present
      loop:
        - git
        - curl

      when: v_name == "devil"               #conditions using when 
