#i took the python as the base image to run this image/container
FROM python
#kept the working directory as first_image to run container
WORKDIR /first_image
#copied the code file i.e goku.txt in container
COPY . /first_image
#command that run goku.txt
CMD ["python","goku.py"]
